version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      # Adicione volumes adicionais conforme necessário para dados persistentes (por exemplo, banco de dados)
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: socialpump
      MYSQL_DATABASE: db_tech
      MYSQL_USER: ramon
      MYSQL_PASSWORD: socialpump
    volumes:
      - ./mysql_data:/var/lib/mysql
    # Adicione mais configurações conforme necessário, como configurações de charset e collation

volumes:
  mysql_data:
